-- One-time Snowflake setup for the cloud path. Run as ACCOUNTADMIN (or a role with equivalent grants).
-- Replace the placeholders in <ANGLE_BRACKETS>.

CREATE WAREHOUSE IF NOT EXISTS MARKETING_WH WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
CREATE DATABASE  IF NOT EXISTS MARKETING;
CREATE SCHEMA    IF NOT EXISTS MARKETING.RAW;
CREATE SCHEMA    IF NOT EXISTS MARKETING.BRONZE;
CREATE SCHEMA    IF NOT EXISTS MARKETING.SILVER;
CREATE SCHEMA    IF NOT EXISTS MARKETING.GOLD;
CREATE SCHEMA    IF NOT EXISTS MARKETING.ANALYTICS;

CREATE ROLE IF NOT EXISTS TRANSFORMER;
GRANT USAGE ON WAREHOUSE MARKETING_WH TO ROLE TRANSFORMER;
GRANT ALL ON DATABASE MARKETING TO ROLE TRANSFORMER;
GRANT ALL ON ALL SCHEMAS IN DATABASE MARKETING TO ROLE TRANSFORMER;
GRANT ALL ON FUTURE TABLES IN DATABASE MARKETING TO ROLE TRANSFORMER;
GRANT ROLE TRANSFORMER TO USER <YOUR_USER>;

USE DATABASE MARKETING;
USE SCHEMA RAW;

-- S3 access via a storage integration (see Snowflake docs: "Configuring a Snowflake storage integration")
CREATE STORAGE INTEGRATION IF NOT EXISTS S3_MARKETING_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = '<arn:aws:iam::ACCOUNT_ID:role/snowflake-s3-access>'
  STORAGE_ALLOWED_LOCATIONS = ('s3://<BUCKET>/<S3_PREFIX>/');

CREATE FILE FORMAT IF NOT EXISTS RAW.NDJSON_FORMAT
  TYPE = JSON
  COMPRESSION = AUTO;

CREATE STAGE IF NOT EXISTS RAW.MARKETING_S3_STAGE
  URL = 's3://<BUCKET>/<S3_PREFIX>/'
  STORAGE_INTEGRATION = S3_MARKETING_INT
  FILE_FORMAT = RAW.NDJSON_FORMAT;

-- RAW tables. Dates stay VARCHAR here; the Bronze models cast them.
CREATE TABLE IF NOT EXISTS RAW.CAMPAIGNS (
  CAMPAIGN_ID VARCHAR, CAMPAIGN_NAME VARCHAR, CHANNEL VARCHAR,
  START_DATE VARCHAR, END_DATE VARCHAR, BUDGET NUMBER(18,2), STATUS VARCHAR,
  _SOURCE_FILE VARCHAR, _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW.AD_PERFORMANCE (
  CAMPAIGN_ID VARCHAR, AD_DATE VARCHAR, IMPRESSIONS NUMBER, CLICKS NUMBER,
  SPEND NUMBER(18,2), CONVERSIONS NUMBER,
  _SOURCE_FILE VARCHAR, _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW.CUSTOMERS (
  CUSTOMER_ID VARCHAR, EMAIL VARCHAR, FIRST_NAME VARCHAR, LAST_NAME VARCHAR,
  COUNTRY VARCHAR, SIGNUP_DATE VARCHAR, MARKETING_OPT_IN BOOLEAN,
  _SOURCE_FILE VARCHAR, _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW.ORDERS (
  ORDER_ID VARCHAR, CUSTOMER_ID VARCHAR, CAMPAIGN_ID VARCHAR, ORDER_DATE VARCHAR,
  ORDER_AMOUNT NUMBER(18,2), STATUS VARCHAR,
  _SOURCE_FILE VARCHAR, _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
